### ISSUE TITLE
Does not build on the first iteration

### ISSUE THREAD

**Issue by AlexisTM** [timn/ros-laser_lines#1]
It seems that the package randomly fails to build the first time as the laser_lines messages is not yet built when the node building process. To reproduce the error, you can use a slower computer or have a lot of packages to 

```gcc
Errors     << laser_lines:make /home/alexis/Workspace/logs/laser_lines/build.make.000.log               
/home/alexis/Workspace/src/laser_lines/src/laser_lines.cpp:24:36: fatal error: laser_lines/LaserLines.h: No such file or directory
```

Can be fixed by adding dependencies for targets at the end of the file:

```cmake
# Deps to the messages
add_dependencies(laser_lines ${${PROJECT_NAME}_EXPORTED_TARGETS} ${catkin_EXPORTED_TARGETS})
add_dependencies(landmark_frame ${${PROJECT_NAME}_EXPORTED_TARGETS} ${catkin_EXPORTED_TARGETS})


```

**Comment by AlexisTM** [comment]
- wrong repo -

**Comment by timn** [comment]
@AlexisTM, I'm still curious. What is the repo this should have gone to, and wouldn't it make sense to still also fix it here? Or are you seeing this only on a modified version of the code? To be fair, I haven't used the code in a while, we are using the [Fawkes version](https://github.com/fawkesrobotics/fawkes/tree/master/src/plugins/laser-lines) mostly.

**Comment by AlexisTM** [comment]
Hey @timn,
I am using @lsy563193 which included the catkin and ROS Kinetic support.

[lsy563193/laser_lines](https://github.com/lsy563193/laser_lines])

On that specific version, the CMakeLists.txt is simply missing the dependency to ensure to build the messages before building the nodes. On the first build, the nodes fails but the messages are built. On the second build, the messages are already built and the node builds with success. 

This version is for fuerte and switching to catkin does include breaking changes. If you have the time for it, you could create a fuerte branch and a kinetic branch or refer to the other repo as the Kinetic version. (there is no algorithm modification between the two forks)

**Comment by timn** [comment]
Care to file a PR?
